version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - '8000:8000'
    command: ['python', 'main.py']
    stdin_open: true
    tty: true
